# Generated by Django 4.1.4 on 2022-12-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pic_share20_api", "0002_alter_users_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="email",
            field=models.CharField(max_length=200, unique=True, verbose_name="メールアドレス"),
        ),
        migrations.AlterField(
            model_name="users",
            name="password",
            field=models.CharField(max_length=200, verbose_name="パスワード"),
        ),
    ]
