# Generated by Django 4.1.4 on 2022-12-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pic_share20_api", "0002_alter_users_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="profile_image",
            field=models.ImageField(
                default="defaultUserIcon_brgqfq", upload_to="images/"
            ),
        ),
    ]
