# Generated by Django 4.1.4 on 2022-12-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pic_share20_api", "0003_alter_users_email_alter_users_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="introduction",
            field=models.TextField(null=True, verbose_name="自己紹介文"),
        ),
    ]
