# Generated by Django 4.1.4 on 2022-12-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pic_share20_api", "0004_alter_users_introduction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="username",
            field=models.CharField(max_length=15, unique=True, verbose_name="ユーザー名"),
        ),
    ]
