# Generated by Django 4.1.4 on 2022-12-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pic_share20_api", "0004_alter_users_profile_image"),
    ]

    operations = [
        migrations.RemoveField(model_name="users", name="id",),
        migrations.AlterField(
            model_name="users",
            name="user_id",
            field=models.CharField(
                max_length=200,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="ユーザーID",
            ),
        ),
    ]
